#!/usr/bin/env bash
set -e

CONFIG_DIR="/root/.hermes"
ENV_FILE="$CONFIG_DIR/.env"
CFG_FILE="$CONFIG_DIR/config.yaml"

mkdir -p "$CONFIG_DIR"

# ---------------------------------------------------------------------------
# Write .env from Dokploy-supplied environment variables.
# The Hermes template ships with every key commented out; we overwrite with a
# minimal, uncommented file containing only the keys we actually have values
# for. Each variable is only written if set in the container environment, so
# unset ones stay absent rather than getting written as empty strings.
# ---------------------------------------------------------------------------
{
	echo "# Generated by entrypoint.sh from container env on $(date -u +%FT%TZ)"
	[ -n "${OPENROUTER_API_KEY:-}" ] && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
	[ -n "${BROWSER_USE_API_KEY:-}" ] && echo "BROWSER_USE_API_KEY=${BROWSER_USE_API_KEY}"
	[ -n "${ANTHROPIC_API_KEY:-}" ] && echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
	[ -n "${GOOGLE_API_KEY:-}" ] && echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}"
	[ -n "${BROWSERBASE_API_KEY:-}" ] && echo "BROWSERBASE_API_KEY=${BROWSERBASE_API_KEY}"
	[ -n "${BROWSERBASE_PROJECT_ID:-}" ] && echo "BROWSERBASE_PROJECT_ID=${BROWSERBASE_PROJECT_ID}"
	[ -n "${TELEGRAM_BOT_TOKEN:-}" ] && echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
	[ -n "${TELEGRAM_ALLOWED_USERS:-}" ] && echo "TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}"
	[ -n "${TELEGRAM_HOME_CHANNEL:-}" ] && echo "TELEGRAM_HOME_CHANNEL=${TELEGRAM_HOME_CHANNEL}"
} >"$ENV_FILE"

# ---------------------------------------------------------------------------
# Patch model.default in config.yaml if HERMES_MODEL is set.
# Matches the first `default: "..."` under the `model:` block.
# ---------------------------------------------------------------------------
if [ -n "${HERMES_MODEL:-}" ] && [ -f "$CFG_FILE" ]; then
	sed -i -E "s|^(  default:).*|\1 \"${HERMES_MODEL}\"|" "$CFG_FILE"
fi

exec "$@"
